### ISSUE TITLE
Introduce an `sql` query parameter for queries

### ISSUE THREAD

**Issue by jamietanna** [frectonz/sql-studio#13]
One of the things that's good about https://datasette.io - an alternative to this project - is the way that SQL queries construct a shareable URL such as https://dependency-management-data-example.fly.dev/datasette/dmd?sql=select+*+from+metadata

It'd be handy if we had the same functionality here, which would allow sharing URLs for i.e. a centrally deployed version of sql-studio

Ideally this would update as the input changes, so the URL is always in-sync with the query being executed

**Comment by frectonz** [comment]
Oh nice, this is also a good idea.

**Comment by jamietanna** [comment]
Maybe covered by https://github.com/frectonz/sql-studio/commit/0d30220a1b438a0dac6b2a9f33da53603ab53f35

**Comment by frectonz** [comment]
Yep it is available in the latest release `0.1.14`.
