### ISSUE TITLE
Set an upper bound (maybe via config) for the `limit` of rows

### ISSUE THREAD

**Issue by jamietanna** [frectonz/sql-studio#14]
When running this against a large database (i.e. ~1M rows in a specific table) and performing a query such as:

```
-- where renovate is the table with ~1M rows
select * from renovate
```

The application locks up.

It may be worth having a limit, which is maybe configurable using a command-line argument, as it's unlikely a user will be wanting the full 1,000,000 rows? It's nice that we _do_ get all the rows instead of truncating it early, but it may be useful to have available as a limited thing, especially for large databases, or centrally deployed instances of `sql-studio`

**Comment by frectonz** [comment]
thanks yeah that's a good feature

**Comment by frectonz** [comment]
I am not sure about implementing this. We now have a timeout feature. I would assume that when a user executes a query they would expect all of the result of their query to be returned to them. Adding a limit to that might create confusion.

I also think the problem of executing on large DBs has been addressed by the timeout.

**Comment by jamietanna** [comment]
I think that's a fair shout, and I'm happy to close this as I see it covered well by the `timeout` config 👍🏼
