### ISSUE TITLE
Postgresql connection issue

### ISSUE THREAD

**Issue by mbecker** [frectonz/sql-studio#21]
Hi,

just wanted to try the sql-stido with my running postgres-docker-instance locally. The docker postgres is running and used by other local running apps (go / rust) without any problems.

I'm trying to start sql-studio as follows
```sh
sql-studio postgres postgres://username123:pasword123@localhost:5432/postgres?sslmode=disable
zsh: no matches found: postgres://username123:pasword123@localhost:5432/postgres?sslmode=disable
```

Suprisingly, the following connection string works:
```sh
sql-studio postgres postgres://username123:pasword123@localhost:5432/postgres
```

**Comment by frectonz** [comment]
The error is not coming from `sql-studio`. It's from `ZSH`. You need to quote the connection string. So that ZSH doesn't think you are writing a glob path.

```zsh
sql-studio postgres "postgres://username123:pasword123@localhost:5432/postgres?sslmode=disable"
```
