### ISSUE TITLE
Postgres schemas

### ISSUE THREAD

**Issue by atefBB** [frectonz/sql-studio#25]
Postgres has a feature called `schemas` which is `a logical container within a database that holds tables, views, indexes, sequences, functions, and other database objects`, when I use sql-studio with my db which contains a lot of schemas it shows only the `public` schema !
Is there an option to see other schemas or it's not supported for now ?

**Comment by frectonz** [comment]
Implemented in `0.1.23`. You can use the `--schema` option.

```
Usage: sql-studio postgres [OPTIONS] <URL>

Arguments:
  <URL>  PostgreSQL connection url [postgresql://postgres:postgres@127.0.0.1/sample]

Options:
  -s, --schema <SCHEMA>  PostgreSQL schema [default: public]
  -h, --help             Print help
```

**Comment by atefBB** [comment]
This option will show a specific schema ? is that correct ? No way to see all schemas in one place ?

**Comment by frectonz** [comment]
Yes,it currently only view one schema at a time. Viewing all schemas will be implemented in future releases.
