### ISSUE TITLE
Improve rendering of incredibly wide tables

### ISSUE THREAD

**Issue by jamietanna** [frectonz/sql-studio#29]
I've got a table that has 26 columns (:face_with_peeking_eye:) and when opening it (with `0.1.17`) I see:

![2024-06-28-085431_1811x67_scrot](https://github.com/frectonz/sql-studio/assets/3315059/fff71345-6afe-4495-b638-9801543be77d)

I wonder if we should:

- add a tooltip (`title` attribute) to each column, to indicate what the text is, in case it's truncated
- allow scrolling horizontally

Thoughts?

**Comment by eznix86** [comment]
I believe the ability to scroll horizontally makes more sense, + have an option to hide columns.

**Comment by frectonz** [comment]
Resizing columns has been implemented in `0.1.23`.

https://github.com/user-attachments/assets/c2f5f81b-e1b4-4412-9f7d-9ca93a00c695
