### ISSUE TITLE
Running `sql-studio` on a distroless image

### ISSUE THREAD

**Issue by jamietanna** [frectonz/sql-studio#33]
This is a tracking image where I'm looking at how I'd be able to run this with as-lightweight-as-possible a Docker image.

Related: #32 

## Chainguard static image

```dockerfile
FROM cgr.dev/chainguard/static:latest

COPY sql-studio /
```

And then when we run this image, we see:

```
exec /sql-studio: no such file or directory
```

## Chainguard static glibc image

```dockerfile
FROM cgr.dev/chainguard/static:latest-glibc

COPY sql-studio /
```

And then when we run this image, we see:

```
exec /sql-studio: no such file or directory
```

## Google distroless static glibc image

```dockerfile
FROM gcr.io/distroless/static-debian12:latest

COPY sql-studio /
```

And then when we run this image, we see:

```
exec /sql-studio: no such file or directory
```

**Comment by jamietanna** [comment]
Via https://images.chainguard.dev/directory/image/static/overview we may need to tweak the build-time flags to produce a fully static image :thinking:

**Comment by jamietanna** [comment]
[via](https://www.linkedin.com/posts/timmcnamaranz_rustlang-activity-7156081873213968384-xLGh):

```
% env RUSTFLAGS='-C target-feature=+crt-static' cargo build
error: cannot produce proc-macro for `async-stream-impl v0.3.5` as the target `x86_64-unknown-linux-gnu` does not support these crate types
```

:(

**Comment by frectonz** [comment]
Related to #31

**Comment by jamietanna** [comment]
Hey @frectonz mind closing this as `Not Planned` in GitHub, rather than `Completed`? It may indicate to others a little better that we did _not_ resolve this, but are closing it as is
