### ISSUE TITLE
Feature request: add a --version (-v) argument to show current version

### ISSUE THREAD

**Issue by AnabasisXu** [frectonz/sql-studio#43]
0.1.27 released yesterday and 

```
❯ sql-studio-update
Checking for updates...
Already up to date; not upgrading
```

So I am not sure whether I am really using 0.1.27. 

Tried to find version information on after lauching the interface, but I could not find it.

Currently the `https://sql-studio.onrender.com/` still shows [0.1.26].

**Comment by frectonz** [comment]
The `--version` flag already exists.

```sh
> sql-studio --version
sql-studio 0.1.272
```

I forgot to update the preview version it is now running `0.1.27`.
https://sql-studio.onrender.com/

Also, `0.1.27` has not been deployed to `Windows` users, if you are a windows user you will either have to use `0.1.26` or use WSL to run `0.1.27`.

**Comment by AnabasisXu** [comment]
Thanks!

It is probably due to Cygwin?
````
❯ sql-studio --version
error: unexpected argument '--version' found

Usage: sql-studio.exe [OPTIONS] <COMMAND>

For more information, try '--help'.
```

Tested `sql-studio --version` in cmder and it shows the version information.
