### ISSUE TITLE
Why use only a single main.rs file？

### ISSUE THREAD

**Issue by logeable** [frectonz/sql-studio#44]
I noticed that there are too many modules and code in main.rs. Why not place different modules in separate files? Wouldn’t that improve maintainability? Can you tell me how you considered this?

**Comment by frectonz** [comment]
I just prefer working with one large file. I think having a lot of smaller files makes a program harder to understand. This is just a personal preference, i have no data to back it up.

**Comment by logeable** [comment]
Thanks for your explanation😀
