### ISSUE TITLE
Features - Implement Auto-Suggestion - SQL Editor

### ISSUE THREAD

**Issue by Victor1890** [frectonz/sql-studio#48]
### Body

Hi @frectonz,

I have a few days to implement autosuggestion to the text editor. Currently, I am working on the keyword's functionality like `SELECT`, `LEFT JOIN`, `WHERE`, etc. but I want to add tables and column names and I need one endpoint to give me that info.

## Before
![image](https://github.com/user-attachments/assets/905f2e4f-1551-4147-b40b-fcddd6312771)

## After
![image](https://github.com/user-attachments/assets/12b1421e-028d-4604-a51c-35019a3bf813)

**Comment by frectonz** [comment]
Thanks for working on this, that sounds like a good idea. What should the endpoint look like? 

Maybe something like this

```
GET /autocomplete
[
    {
        table_name: "test".
        columns: ["id", "name"]
    }
]
```

**Comment by Victor1890** [comment]
Exactly

**Comment by Victor1890** [comment]
Thanks, I'll to work this feature.

**Comment by Victor1890** [comment]
#49
