### ISSUE TITLE
Fix error when I'm trying to build the project

### ISSUE THREAD

**Issue by Victor1890** [frectonz/sql-studio#50]
## Fix error when I'm trying to build the project

If you get an error when you build or run the `libduckdb-sys v0.10.2` project on Windows WLS, you should do this pre-configuration.
You must create (if you don't have it) `.wslconfig` file in `C:\users\USERNAME` and add or change the following properties

```yaml
[wsl2]

#Limits VM memory to use no more than 4 GB, this can be set as whole numbers using GB or MB
memory=6GB

#Sets the VM to use two virtual processors
processors=6
```

**PR of reference**: #39

**Comment by frectonz** [comment]
Thanks for providing this fix, i will inform anyone who is facing an issue build sql studio in WSL of this fix. 

For now i will close this issue since it's not technically "issue".
