### ISSUE TITLE
GLIBC_2.29 not found errors

### ISSUE THREAD

**Issue by kyilmaz** [frectonz/sql-studio#53]
I have encountered issues to run sql-studio that;

1) preCompiled:
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by sql-studio-x86_64-unknown-linux-gnu/sql-studio)
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by sql-studio-x86_64-unknown-linux-gnu/sql-studio)
/lib64/libc.so.6: version `GLIBC_2.29' not found (required by sql-studio-x86_64-unknown-linux-gnu/sql-studio)

2) tried to run from sql-studio-installer.sh: 
System glibc version (`2.28') is too old; checking alternatives
ERROR: no compatible downloads were found for your platform x86_64-unknown-linux-gnu

3) tried to run from curl:
$ curl --proto '=https' --tlsv1.2 -LsSf https://github.com/frectonz/sql-studio/releases/download/0.1.32/sql-studio-installer.sh | sh
System glibc version (`2.28') is too old; checking alternatives
ERROR: no compatible downloads were found for your platform x86_64-unknown-linux-gnu

specs of;
gcc = gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
os = "Rocky Linux 8.10 (Green Obsidian)"
kern =  4.18.0-553.22.1.el8_10.x86_64

How can i to do run  "sql-studio" ?

Thanks ...

**Comment by frectonz** [comment]
You can use the [docker image](https://github.com/frectonz/sql-studio#docker).
